### ISSUE TITLE
Meeting - WENSDAY: August 10, 2016 @ 12:00 AM EST / 5:00 BST / 6:00 CEST

### ISSUE THREAD

**Issue by wanderer** [ethereum/evm2.0-design#19]
This is a planning issue for next Mondays weekly meeting. Here is the link https://meet.jit.si/DizzyGorillasRejoiceAlone
@gcolvin says the 10:00 AM is too early. If we move to 11:00 AM will that be too late for @axic @chriseth ?

Also feel free to add comments for agenda items.

**Comment by chriseth** [comment]
Sorry, I have conflicts on both times, in general that day is not the best for me.

**Comment by wanderer** [comment]
@chriseth what day would work for you?

**Comment by wanderer** [comment]
oh yeah we have the core meeting at that time on monday. Does tuesday work for everyone?

**Comment by chriseth** [comment]
I would prefer wednesday if that's ok.

**Comment by wanderer** [comment]
ok Wednesday works, is the time 11:00 AM EST/4:00 CEST good for you?

**Comment by axic** [comment]
Can we do it 12:00 AM EST / 4:00 BST / 5:00 CEST?

Another suggestion: keep the very same jitsi channel for every session, so there's no confusion where to talk.

**Comment by wanderer** [comment]
ok @axic updated to 12:00
