### ISSUE TITLE
Bootstrapping into useful testing phase

### ISSUE THREAD

**Issue by axic** [ethereum/evm2.0-design#2]
It would be fairly simple to move this from an isolated test into a more useful testing framework by adjusting one of the VM implementations.

The adjustment would include to run the eWASM VM when a contract bytecode starts with the WASM bytecode signature (`\0asm`).

This can be easily achieved by using `ethereumjs-vm`, which then would provide a state and full blockchain.

Depending on ABI decision (https://github.com/ethereum/evm2.0-design/issues/1), wrapper methods for `callCode` and `delegateCall` might be needed to transform between the new and current ABIs.

**Comment by wanderer** [comment]
I think this would be good for a test network. I'm not sure if it will suffice for the whole network yet though. One concern with putting something like this on the live network would be 2 the surface area for consensus breaking bugs

**Comment by axic** [comment]
Also prefixing the bytecode with an EVM1 code piece (e.g. `RETURN` to stop execution) could make this compatible with the current network. An EVM1 contract deployment code would be needed also.

**Comment by axic** [comment]
As a note, WASM prototype-1 had a magic string of `wasm`, while prototype-2 has `\0asm`.

**Comment by axic** [comment]
This backwards compatible part is now incorporated into #42.

There's a VM in progress with the above considered: https://github.com/ewasm/ewasm-kernel
