### ISSUE TITLE
optionally merkle-ized storage

### ISSUE THREAD

**Issue by nmushegian** [ethereum/evm2.0-design#33]
My understanding is that the only function of merkleizing the entire storage space is for thin client support. I wonder this is an opportunity to introduce an optional storage space which is not summarized at all. The burden of proof is on the dapp dev if they want to use this space and roll their own app-level thin client proof solution.

For some apps the limiting factor for transaction bandwidth is plain old cpu speed on one thread. Sharding is not enough to be competitive with centralized exchanges or architectures like bitshares

**Comment by wanderer** [comment]
> My understanding is that the only function of merkleizing the entire storage space is for thin client support.

Its for consensus in general, Everything in the state need to be in the finally block's state root for miners/validators to agree on and I don't really think there is away around that.

**Comment by nmushegian** [comment]
Putting it in the state root makes your consensus failures instant instead of delayed, but sure, let's say we want that. Even so I don't think the summary has to support full merkle proofs of arbitrary storage slots, you could zip the state and do a single hash for the whole block. Right now Solidity encourages a hash *per lookup* since that's how `mapping`s work

**Comment by wanderer** [comment]
> you could hash the entire unmerklized state once for the whole bloc

The point of merkle trie is that it is more efficient than just hashing all the keys in a dictionary. I'm not sure how `mapping` works but an efficient ethereum implementation only will have to create a global state root once for each block, and storage state root per contract that changed its storage in that given block** 

**pending upcoming metropolis changes, reality now is one global state root per tx

**Comment by nmushegian** [comment]
> the point of merkle trie is that it is more efficient than just hashing all the keys in a dictionary.

Fine but I'm sure there's still some incremental hash strategy where you don't have to have an entire *tree* of hashes that supports a full merkle proof.

But in any case, isn't a hash of the trx IDs the only summary you *actually* need for full nodes to reach consensus? I don't see why they need state summary at all except 1) thin clients and 2) to detect potential consensus failures earlier. If this is true there ought to be a way to utilize that tradeoff on purpose, if not I'd like to understand the design motives more

**Comment by wanderer** [comment]
> But in any case, isn't a hash of the trx IDs the only summary you actually need for full nodes to reach consensus?

The stateRoot shows that the computation was done. But yes you are right, there could be a system were you didn't have the stateRoot at all.  And you could use something like logs to put all contracts to put stateRoot in the blockheader if they wanted to be light client friendly.

**Comment by wanderer** [comment]
Looking into implementing the merkle-trie itself as a contract would be the first step here.

**Comment by axic** [comment]
@nmushegian @wanderer wouldn't this discussion belong to https://github.com/ethereum/EIPs?

**Comment by wanderer** [comment]
@axic yep, closes for now. @nmushegian feel free to reopen  in the EIPs repo
