### ISSUE TITLE
add Gregs VM to the VM comparisons 

### ISSUE THREAD

**Issue by wanderer** [ethereum/evm2.0-design#9]
https://github.com/ethereum/evm2.0-design/blob/master/comparison.md

**Comment by leithaus** [comment]
[SynereDevWorkshopNotes.pdf](https://github.com/ethereum/evm2.0-design/files/257732/SynereDevWorkshopNotes.pdf)
[CasperInRHOVII.pdf](https://github.com/ethereum/evm2.0-design/files/257734/CasperInRHOVII.pdf)

In the hangout i mentioned that i'm slightly more partial to the OCaml approach for the map from lambda to LLVM. Here's what i'm talking about: https://github.com/leithaus/davinci/blob/master/doc/ZincJIT.pdf

The OCaml machine is call Zinc. There's a jit from Zinc to LLVM.
